//
// Copyright (c) 2025, Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import Foundation

/// Data structure representing the result of a signing operation.
public struct SignResult: Decodable {

    /// The signature generated by the signing operation (in hexadecimal format).
    public let signature: String

    /// The WebAuthn data associated with the signing operation.
    public let webAuthn: WebAuthnData

    /// The raw authentication credential used in the signing operation.
    public let raw: AuthenticationCredential
}

/// Data structure representing WebAuthn data.
public struct WebAuthnData: Decodable {

    /// The authenticator data (in hexadecimal format).
    public let authenticatorData: String

    /// The client data JSON (Base64URL decoded).
    public let clientDataJSON: String

    /// The index of the challenge in the client data JSON.
    public let challengeIndex: Int

    /// The index of the type in the client data JSON.
    public let typeIndex: Int

    /// Indicates whether user verification is required.
    public let userVerificationRequired: Bool
}

extension AuthenticationCredential {

    func toWebAuthnData(userVerification: String) -> WebAuthnData? {
        guard let response = response as? AuthenticatorAssertionResponse else {
            return nil
        }

        let decodedJSON = String(bytes: response.clientDataJSON.decodedBytes ?? [], encoding: .utf8) ?? ""
        let authenticatorData = HexUtils.bytesToHex(response.authenticatorData.decodedBytes)
        let challengeIndex: Int = decodedJSON.index(of: "\"challenge\"") ?? 0
        let typeIndex: Int = decodedJSON.index(of: "\"type\"") ?? 0

        return WebAuthnData(
            authenticatorData: authenticatorData,
            clientDataJSON: decodedJSON,
            challengeIndex: challengeIndex,
            typeIndex: typeIndex,
            userVerificationRequired: userVerification == UserVerificationRequirement.required.rawValue
        )
    }
}
